### ISSUE TITLE
`OutputTree.deleteNode`: Consider passing the child's position

### ISSUE THREAD

**Issue by rigdern** [briskml/brisk-reconciler#10]
The index of the child to remove would be useful for rendering to some kinds of platforms. For example, React Native bases its removals on indices: https://github.com/facebook/react-native/blob/1af390be19000b2756fc646e72f152dd383a0bb1/React/Modules/RCTUIManager.m#L845

If brisk-reconciler has this information easily available, it would be convenient to pass it along. If not, it's not a big deal. The consumer of brisk-reconciler can create a data structure to store the node positions and update it in `insertNode` and `moveNode`.

**Comment by wokalski** [comment]
This information is available. I will try to squeeze it in this week.
