### ISSUE TITLE
Adopt relevant parts of React.js's test suite

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk-reconciler#11]
We need a solid test suite. I don't think there exists a better place to take tests from than react js repo. We are probably going to need ot modify a fair share of them and discard some (both because brisk doesn't aim for feature parity with react and that we might have different semantics for some cases.)

**Comment by bryphe** [comment]
Great idea @wokalski !

**Comment by wokalski** [comment]
This is too far fetched to ever become reality. Also, brisk is diverging from react.js in many subtle ways.
