### ISSUE TITLE
Set up CI for windows

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk-reconciler#2]
Certain dependencies don't build on windows like `ppx_deriving` which we're using for tests. Adding the platform itself to the CI pipeline is very easy (https://github.com/briskml/brisk-reconciler/commit/17b79770806683940588af3a5791e449097b767a) however the build fails.

**Comment by bryphe** [comment]
`ppx_deriving` is actually fine, but `alcotest`, `patience_diff` and `easy-format` are problematic on Windows.

Would you consider switching to [`rely`](https://github.com/facebookexperimental/reason-native/tree/master/src/rely)? I'm going to be using that as the test runner for Revery too shortly.

**Comment by wokalski** [comment]
Oh yes - definitely. If it's just alcotest and the formatters we will definitely switch to rely. I thought that it was one of transitive dependencies of ppx_deriving that failed. Thanks!

**Comment by bryphe** [comment]
I actually have this project that uses `ppx_deriving` and [builds on Windows](https://bryphe.visualstudio.com/merlin-language-server/_build/results?buildId=1236) - https://github.com/bryphe/merlin-language-server (just as a reference). Happens to use `rely`, too!

**Comment by wokalski** [comment]
Fixed in #59
