### ISSUE TITLE
Developer Experience: Stale `set` functions from Hooks

### ISSUE THREAD

**Issue by bryphe** [briskml/brisk-reconciler#26]
After upgrading to latest brisk - we experienced a couple regressions in our functionality:
- Slider control was no longer updating (#342)
- Scroll bounce was no longer working (#346)

These occurred after the update to the immutable hooks API: https://github.com/revery-ui/revery/commit/eda0fe65a38aa3a3793e00d7750478a5df51c5da

The issue was a problem in our code - we had long-lived closures that held on to `set` functions past re-renders. For #346 , for example, a fix was to switch to a shorter-lived `effect` hook. 

However, it wasn't very diagnosable - we just started seeing unexpected behavior when we used the `set` functions in this way.  It'd be helpful if we could at least detect this case - that we're calling a stale `set` and throw a descriptive error - like how the React devtools warn. 

A message like `ERROR: Stale setter used for reducer hook; check that you aren't holding a setter in a long-lived function` would be helpful to catch the error close to the source.

**Comment by wokalski** [comment]
@bryphe a good solution here is using a reducer. It works with stale setters. The rationale is that reducers are naturally built with all kinds of race conditions in mind. With setState it’s often the case that setters are passed around and invoked accidentally

**Comment by bryphe** [comment]
Thanks @wokalski ! For some reason I thought I had the same issue with reducer, but I just tried and it seems like that scenario works.

I still think we should have something here in place - at least something diagnosable, since this stale-setter behavior differs from ReactJS.

**Comment by wokalski** [comment]
We will have a very elaborate warning here.
