### ISSUE TITLE
Allow declaring components on one line

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk-reconciler#28]
The current dance with:

```reason
let c = component("name");
let somethingElse = (~prop, ~prop, ()) => component(hooks => ...
```

is really annoying. It feels like using something very rough unpolished. We should strive to make possible the following:

```
let somethingElse = component((~prop, ~prop, ()) => ...)
```

**Comment by ducaale** [comment]
Maybe it can be simplified with a ppx just like in reason-react? 
Then the same ppx can be used to remove the need for threading hooks by users https://github.com/briskml/brisk-reconciler/issues/6#issuecomment-462078721

**Comment by wokalski** [comment]
@ducaale I tried to avoid PPX at first but now I think it's the best option. I'm already working on it.
