### ISSUE TITLE
Switch to Rely test runner

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk-reconciler#3]
According to @bryphe [Rely](
https://github.com/facebookexperimental/reason-native/tree/master/src/rely) alleviates some of our problems with building for windows (#2). Rely also has quite a few nice features and mostly removes the need for our own diffing which is awesome.

**Comment by wokalski** [comment]
@Prabhakar-17 in https://github.com/briskml/brisk/pull/48, @rauanmayemir did it for Brisk. I think it might be helpful to you. IIRC he also did some experiments for the brisk-reconciler.

Thanks!

**Comment by Prabhakar-17** [comment]
@wokalski Thanks, this is helpful. @rauanmayemir I would like to know if you have already done some work on this?

**Comment by rauanmayemir** [comment]
@Prabhakar-17 I wanted to see if it's possible to improve our testing infra and it looks like it could be done.

E.g instead of this:

```
render(<Components.BoxWrapper />)
|> executeSideEffects
|> expect(
      ~label="It correctly inserts nodes",
      [
        Implementation.BeginChanges,
        MountChild(div, box("ImABox"), 0),
        MountChild(root, div, 0),
        CommitChanges,
      ],
    )
|> ignore,
```

Have this:

```
describe("Test initial render", ({test}) =>
  test("It should correctly insert nodes", ({expect}) => {
    let state = render(<Components.BoxWrapper />) |> executeSideEffects;
    let snapshot = [
      Implementation.BeginChanges,
      MountChild(div, box("ImABox"), 0),
      MountChild(root, div, 0),
      CommitChanges,
    ];

    expect.ext.mounted(state).toMatch(snapshot);
  })
);
```

Or even do something like this:

```
expect.ext.rendered(<Components.BoxWrapper />)
  .withSideEffects.toMatch(snapshot);
```

So the way to achieve that is to use Rely's CustomMatcher facilities, relevant example: https://github.com/facebookexperimental/reason-native/blob/9643b5e19697fba5d846020cbc2fc1e393888bb5/tests/__tests__/rely/CustomMatchers_test.re

This would streamline the experience and provide better output. Feel free to tackle it.

**Comment by wokalski** [comment]
@Prabhakar-17 feel free to DM me on discord if you have any type system puzzles 😃

**Comment by wokalski** [comment]
When this is done, remember to add windows to the test matrix.

https://github.com/briskml/brisk-reconciler/pull/55/files#diff-fec826feae04e51c0d94076385408bdcR9-R11

**Comment by ulrikstrid** [comment]
When this is done I'll add jUnit for even nicer reports in CI, commenting to get notified an remember.

**Comment by wokalski** [comment]
Fixed by @ulrikstrid
